#change configfile to point to experiment_info.yaml for this experiment
#change mkdir, --output and --error to point to log folder for this experiment
#change mail-user, mail-type to point to your email
#can change default resources or set-resources as needed


snakefile: Snakefile
use-conda: True
conda-prefix: /PATH/TO/PRELOADED/CONDA/ENVS
conda-frontend: mamba
rerun-incomplete: True
restart-times: 1
jobs: 100
latency-wait: 30
keep-going: True
configfile: ./experiment_info.yaml
rerun-triggers: mtime

# modify if necessary
cluster-status: ./scripts/slurm_status_script.py
reason: True
# dryrun: True
# unlock: True

cluster:
  sbatch
    --ntasks={resources.ntasks}
    --cpus-per-task={resources.cpus_per_task}
    --mem={resources.mem}
    --time={resources.time}
    --job-name="SM.{rule}"
    --output="./logs/%j_{rule}.out.txt"
    --error="./logs/%j_{rule}.err.txt"
    --mail-user="UPDATE_EMAIL_ADDRESS"
    --mail-type="FAIL"
#    --partition={resources.partition}
#    --exclude="node035,node390"

#note that resource names should use underscore _ instead of dash -

default-resources:
   - time="1:00:00"
   - ntasks=1
   - cpus_per_task=1
   - mem="8G"
#   - partition=""
#   - tmpdir='/other/tmp/dir'

set-resources:
   # make_data_links (runs all link generation at once)
   - make_data_links:ntasks=1
   - make_data_links:cpus_per_task=1
   - make_data_links:time="00:30:00"
   - make_data_links:mem=1G
   # cutadapt
   - cutadapt:ntasks=1
   - cutadapt:cpus_per_task=1
   - cutadapt:time="04:00:00"
   # sickle
   - sickle:ntasks=1
   - sickle:cpus_per_task=1
   - sickle:time="04:00:00"
   # bowtie2
   - bowtie2:mem=64G
   - bowtie2:cpus_per_task=8
   - bowtie2:time="02:00:00"
   # sam2bam
   - sam2bam:mem=64G
   - sam2bam:cpus_per_task=1
   - sam2bam:time="12:00:00"
   # sam2bam_cleanup
   - sam2bam_cleanup:mem=4G
   - sam2bam_cleanup:cpus_per_task=1
   - sam2bam_cleanup:time="00:30:00"
   # mpileup2vcf
   - mpileup2vcf:mem=60G
   - mpileup2vcf:cpus_per_task=1
   - mpileup2vcf:time="12:00:00"
   # pileup2diversity_matrix
   - pileup2diversity_matrix:mem=60G
   - pileup2diversity_matrix:cpus_per_task=1
   - pileup2diversity_matrix:time="12:00:00"
   # variants2positions
   - variants2positions:mem=60G
   - variants2positions:mem_per_cpu=60G
   - variants2positions:cpus_per_task=1
   - variants2positions:time="02:00:00"
   # combine_positions
   - combine_positions:mem=60G
   - combine_positions:mem_per_cpu=60G
   - combine_positions:cpus_per_task=1
   - combine_positions:time="02:00:00"
   # build_data_links
   - build_data_links:mem=8G
   - build_data_links:mem_per_cpu=8G
   - build_data_links:cpus_per_task=1
   - build_data_links:time="12:00:00"
   # kraken2
   - kraken2:mem=64G
   - kraken2:cpus_per_task=20
   - kraken2:time="05:00:00"
   # bracken
   - bracken:mem=64G
   - bracken:cpus_per_task=20
   - bracken:time="05:00:00"
   # spades
   - spades:mem=100G
   - spades:cpus_per_task=16
   - spades:time="12:00:00"
   # sumstats
   - sumstats:mem=10G
   # prokka
   - prokka:mem=64G
   - prokka:cpus_per_task=16
   - prokka:time="04:00:00"
   # infer_orthologs (group)
   - infer_orthologs:mem=8G
   - infer_orthologs:cpus_per_task=1
   - infer_orthologs:time="04:00:00"
